import 'server-only';

import type { ModelCatalogueEntry } from '../lib/server/providers/types';

/**
 * The M1 model catalogue — api-contract.md §3.5, fixed and frozen. `id` values are load-bearing:
 * A4 (CP-004/CP-005) references these exact strings, and A5 (T-005) names its preview art
 * `public/brand/models/<id>.svg` after them.
 *
 * Server-only: `upstreamModel` never reaches a DTO — `registry.toModelSummary()` strips it, along
 * with `providerId` and the raw `previewAssetPath` key, per architecture.md §4.
 */

const IMAGE_ASPECT_RATIOS = ['1:1', '16:9', '9:16', '4:3', '3:4'];
const VIDEO_ASPECT_RATIOS = ['16:9', '9:16', '1:1'];
const VIDEO_MAX_DURATION_SECONDS = 5;

export const MODELS: ModelCatalogueEntry[] = [
  {
    id: 'nano-banana-2',
    providerId: 'mock',
    upstreamModel: 'nano-banana/v2.1-image',
    displayName: 'Nano Banana 2',
    kind: 'image',
    tier: 'premium',
    badges: ['latest'],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 5,
    previewAssetPath: '/brand/models/nano-banana-2.svg',
    available: true,
    priceCredits: 600,
    featured: true,
  },
  {
    id: 'gpt-image-2',
    providerId: 'mock',
    upstreamModel: 'openai/gpt-image-2-2026-06',
    displayName: 'GPT-Image 2',
    kind: 'image',
    tier: 'premium',
    badges: [],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 6,
    previewAssetPath: '/brand/models/gpt-image-2.svg',
    available: true,
    priceCredits: 600,
    featured: true,
  },
  {
    id: 'kling-2-5',
    providerId: 'mock',
    upstreamModel: 'kling/v2.5-pro-video',
    displayName: 'Kling 2.5',
    kind: 'video',
    tier: 'premium',
    badges: ['latest'],
    aspectRatios: [...VIDEO_ASPECT_RATIOS],
    maxDurationSeconds: VIDEO_MAX_DURATION_SECONDS,
    estimatedSeconds: 14,
    previewAssetPath: '/brand/models/kling-2-5.svg',
    available: true,
    priceCredits: 12000,
    featured: true,
  },
  {
    id: 'seedance-2-5',
    providerId: 'mock',
    upstreamModel: 'seedance/v2.5-video',
    displayName: 'Seedance 2.5',
    kind: 'video',
    tier: 'mid',
    badges: ['latest'],
    aspectRatios: [...VIDEO_ASPECT_RATIOS],
    maxDurationSeconds: VIDEO_MAX_DURATION_SECONDS,
    estimatedSeconds: 12,
    previewAssetPath: '/brand/models/seedance-2-5.svg',
    available: true,
    priceCredits: 5000,
    featured: true,
  },
  {
    id: 'grok-image-1',
    providerId: 'mock',
    upstreamModel: 'xai/grok-image-1',
    displayName: 'Grok Image',
    kind: 'image',
    tier: 'mid',
    badges: [],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 4,
    previewAssetPath: '/brand/models/grok-image-1.svg',
    available: true,
    priceCredits: 250,
    featured: false,
  },
  {
    id: 'flux-schnell',
    providerId: 'mock',
    upstreamModel: 'blackforest/flux-schnell',
    displayName: 'Flux Schnell',
    kind: 'image',
    tier: 'budget',
    badges: ['fast'],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 2,
    previewAssetPath: '/brand/models/flux-schnell.svg',
    available: true,
    priceCredits: 30,
    featured: false,
  },
  {
    id: 'sdxl-turbo',
    providerId: 'mock',
    upstreamModel: 'stability/sdxl-turbo',
    displayName: 'SDXL Turbo',
    kind: 'image',
    tier: 'budget',
    badges: ['fast'],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 2,
    previewAssetPath: '/brand/models/sdxl-turbo.svg',
    available: true,
    priceCredits: 30,
    featured: false,
  },
  {
    id: 'imagen-4-ultra',
    providerId: 'mock',
    upstreamModel: 'google/imagen-4-ultra',
    displayName: 'Imagen 4 Ultra',
    kind: 'image',
    tier: 'high_end',
    badges: [],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 9,
    previewAssetPath: '/brand/models/imagen-4-ultra.svg',
    available: true,
    priceCredits: 1200,
    featured: false,
  },
  {
    id: 'midjourney-7',
    providerId: 'mock',
    upstreamModel: 'midjourney/v7',
    displayName: 'Midjourney 7',
    kind: 'image',
    tier: 'high_end',
    badges: [],
    aspectRatios: [...IMAGE_ASPECT_RATIOS],
    estimatedSeconds: 10,
    previewAssetPath: '/brand/models/midjourney-7.svg',
    available: true,
    priceCredits: 1200,
    featured: false,
  },
  {
    id: 'hailuo-02',
    providerId: 'mock',
    upstreamModel: 'minimax/hailuo-02',
    displayName: 'Hailuo 02',
    kind: 'video',
    tier: 'budget',
    badges: ['fast'],
    aspectRatios: [...VIDEO_ASPECT_RATIOS],
    maxDurationSeconds: VIDEO_MAX_DURATION_SECONDS,
    estimatedSeconds: 10,
    previewAssetPath: '/brand/models/hailuo-02.svg',
    available: true,
    priceCredits: 2500,
    featured: false,
  },
  {
    id: 'wan-2-5',
    providerId: 'mock',
    upstreamModel: 'alibaba/wan-2.5',
    displayName: 'Wan 2.5',
    kind: 'video',
    tier: 'mid',
    badges: [],
    aspectRatios: [...VIDEO_ASPECT_RATIOS],
    maxDurationSeconds: VIDEO_MAX_DURATION_SECONDS,
    estimatedSeconds: 12,
    previewAssetPath: '/brand/models/wan-2-5.svg',
    available: true,
    priceCredits: 5000,
    featured: false,
  },
  {
    id: 'veo-3-1',
    providerId: 'mock',
    upstreamModel: 'google/veo-3.1',
    displayName: 'Veo 3.1',
    kind: 'video',
    tier: 'high_end',
    badges: [],
    aspectRatios: [...VIDEO_ASPECT_RATIOS],
    maxDurationSeconds: VIDEO_MAX_DURATION_SECONDS,
    estimatedSeconds: 18,
    previewAssetPath: '/brand/models/veo-3-1.svg',
    available: true,
    priceCredits: 24000,
    featured: false,
  },
];
